apiVersion: v1
kind: Namespace
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "-2"
  name: power-monitoring
---
apiVersion: kepler.system.sustainable.computing.io/v1alpha1
kind: Kepler
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "0"
  labels:
    app.kubernetes.io/instance: kepler
    app.kubernetes.io/name: kepler
    app.kubernetes.io/part-of: kepler-operator
  name: kepler
spec:
  exporter:
    deployment:
      port: 9103
      tolerations:
      - operator: Exists
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "-2"
    olm.providedAPIs: Kepler.v1alpha1.kepler.system.sustainable.computing.io,KeplerInternal.v1alpha1.kepler.system.sustainable.computing.io
  name: power-monitoring
  namespace: power-monitoring
spec:
  upgradeStrategy: Default
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "-1"
  labels:
    operators.coreos.com/power-monitoring-operator.power-monitoring: ""
  name: power-monitoring-operator
  namespace: power-monitoring
spec:
  channel: tech-preview
  installPlanApproval: Automatic
  name: power-monitoring-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: power-monitoring-operator.v0.2.0
