apiVersion: v1
kind: ServiceAccount
metadata:
  name: crossplane-sa
  namespace: crossplane-config
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: crossplane-clusterrole
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  - secrets
  - serviceaccounts
  verbs:
  - '*'
- apiGroups:
  - authorization.openshift.io
  - rbac.authorization.k8s.io
  resources:
  - roles
  - rolebindings
  verbs:
  - '*'
- apiGroups:
  - networking.k8s.io
  resources:
  - networkpolicies
  verbs:
  - '*'
- apiGroups:
  - quota.openshift.io
  resources:
  - resourcequotas
  - clusterresourcequotas
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: crossplane-crb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: crossplane-clusterrole
subjects:
- kind: ServiceAccount
  name: crossplane-sa
  namespace: crossplane-config
---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    kubernetes.io/service-account.name: crossplane-sa
  name: crossplane-secret
  namespace: crossplane-config
type: kubernetes.io/service-account-token
