apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: workspaces-manager
  namespace: rhtap-auth
rules:
- apiGroups:
  - keycloak.org
  resources:
  - keycloakusers
  verbs:
  - get
  - list
  - update
  - patch
  - create
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: konflux-workspace-admins
  namespace: rhtap-auth
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: workspaces-manager
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: konflux-workspace-admins
