apiVersion: v1
kind: Namespace
metadata:
  name: spacerequest-cleaner
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: spacerequest-cleaner
  namespace: spacerequest-cleaner
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: spacerequest-cleaner
rules:
- apiGroups:
  - toolchain.dev.openshift.com
  resources:
  - spacerequests
  verbs:
  - list
  - delete
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: spacerequest-cleaner
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: spacerequest-cleaner
subjects:
- kind: ServiceAccount
  name: spacerequest-cleaner
  namespace: spacerequest-cleaner
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: spacerequest-cleaner
  namespace: spacerequest-cleaner
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - command:
            - clean_spacerequests
            image: quay.io/redhat-appstudio/tools:2c47ed424b6b150445a45f34569f7dcce9ebad71
            imagePullPolicy: Always
            name: spacerequest-cleaner
            resources:
              limits:
                cpu: 250m
                memory: 125Mi
              requests:
                cpu: 250m
                memory: 125Mi
            securityContext:
              readOnlyRootFilesystem: true
              runAsNonRoot: true
          restartPolicy: Never
          serviceAccountName: spacerequest-cleaner
  schedule: 0 4 * * *
