apiVersion: v1
kind: Namespace
metadata:
  name: openshift-adp
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
  name: backup-s3-credentials
  namespace: openshift-adp
spec:
  dataFrom:
  - extract:
      conversionStrategy: Default
      decodingStrategy: None
      key: integrations-output/terraform-resources/stonesoups01ue1/stonesoup-infra-stage-backup/backup-stone-stg-m01
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: appsre-vault
  target:
    creationPolicy: Owner
    deletionPolicy: Delete
    name: backup-s3-credentials
    template:
      data:
        cloud: |
          [default]
          aws_access_key_id={{ .aws_access_key_id }}
          aws_secret_access_key={{ .aws_secret_access_key }}
