apiVersion: v1
kind: Namespace
metadata:
  name: openshift-adp
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
  name: backup-s3-credentials
  namespace: openshift-adp
spec:
  dataFrom:
  - extract:
      conversionStrategy: Default
      decodingStrategy: None
      key: integrations-output/terraform-resources/appsres09ue1/stonesoup-infra-stage-backup/backup-stone-stg-rh01
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: appsre-vault
  target:
    creationPolicy: Owner
    deletionPolicy: Delete
    name: backup-s3-credentials
    template:
      data:
        cloud: |
          [default]
          aws_access_key_id={{ .aws_access_key_id }}
          aws_secret_access_key={{ .aws_secret_access_key }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: oadp-service-monitor
  name: oadp-service-monitor
  namespace: openshift-adp
spec:
  endpoints:
  - interval: 30s
    path: /metrics
    scheme: http
    targetPort: 8085
  selector:
    matchLabels:
      app.kubernetes.io/name: velero
---
apiVersion: oadp.openshift.io/v1alpha1
kind: DataProtectionApplication
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "-1"
  name: velero-aws
  namespace: openshift-adp
spec:
  backupLocations:
  - velero:
      config:
        kmsKeyId: f1db03bc-ea5b-48f8-a40b-1afbbe666178
        profile: default
        region: us-east-1
      credential:
        key: cloud
        name: backup-s3-credentials
      default: true
      objectStorage:
        bucket: backup-stone-stg-rh01
        prefix: velero
      provider: aws
  configuration:
    restic:
      enable: false
    velero:
      defaultPlugins:
      - openshift
      - aws
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
  name: openshift-adp
  namespace: openshift-adp
spec:
  targetNamespaces:
  - openshift-adp
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
  name: redhat-oadp-operator
  namespace: openshift-adp
spec:
  channel: stable-1.3
  installPlanApproval: Automatic
  name: redhat-oadp-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
---
apiVersion: velero.io/v1
kind: Schedule
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  name: backup-tenants
  namespace: openshift-adp
spec:
  schedule: 30 1,13 * * *
  template:
    excludedNamespaces:
    - kube-*
    - openshift*
    - appstudio*
    - admin-checker
    - application-api
    - application-service
    - appsre-vault
    - build-service
    - build-templates
    - build-templates-e2e
    - ci-helper-app
    - dedicated-admin
    - deployment-validation-operator
    - dora-metrics
    - enterprise-contract-service
    - external-secrets-operator
    - gitops
    - gitops-service-argocd
    - group-sync-operator
    - hac-pact-broker
    - image-controller
    - integration-service
    - internal-services
    - jvm-build-service
    - multi-platform-controller
    - perf-team-prometheus-reader
    - plnsvc-tests
    - quality-dashboard
    - release-service
    - sandbox-sre-member
    - tekton-results
    - toolchain-member-operator
    includedResources:
    - applications.appstudio.redhat.com
    - components.appstudio.redhat.com
    - environments.appstudio.redhat.com
    - integrationtestscenarios.appstudio.redhat.com
    - secrets
    - snapshots.appstudio.redhat.com
    - serviceaccounts
    - namespaces
    storageLocation: velero-aws-1
    ttl: 720h0m0s
  useOwnerReferencesInBackup: true
---
apiVersion: velero.io/v1
kind: Schedule
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  name: backup-toolchain-member
  namespace: openshift-adp
spec:
  schedule: 30 1,13 * * *
  template:
    includedNamespaces:
    - toolchain-member-operator
    storageLocation: velero-aws-1
    ttl: 720h0m0s
  useOwnerReferencesInBackup: true
