apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ci-helper-app-maintainer
  namespace: ci-helper-app
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  - pods
  verbs:
  - create
  - delete
  - edit
  - get
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ci-helper-app-maintainers
  namespace: ci-helper-app
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ci-helper-app-maintainer
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: konflux-qe-admins
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ci-helper-app
  name: ci-helper-app
  namespace: ci-helper-app
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: ci-helper-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ci-helper-app
  name: ci-helper-app
  namespace: ci-helper-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ci-helper-app
  template:
    metadata:
      labels:
        app: ci-helper-app
    spec:
      containers:
      - command:
        - /ci-helper-app
        env:
        - name: GITHUB_APP_INTEGRATION_ID
          valueFrom:
            secretKeyRef:
              key: app-id
              name: ci-helper-app-secrets
        - name: GITHUB_APP_WEBHOOK_SECRET
          valueFrom:
            secretKeyRef:
              key: webhook-secret
              name: ci-helper-app-secrets
        - name: GITHUB_APP_PRIVATE_KEY
          valueFrom:
            secretKeyRef:
              key: app-private-key
              name: ci-helper-app-secrets
        image: quay.io/konflux-ci/ci-helper-app:c74e02a133e09ed7cbb628919aaaa5cd3325375d
        name: ci-helper-app
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 256Mi
          requests:
            cpu: 10m
            memory: 128Mi
        securityContext:
          readOnlyRootFilesystem: true
          runAsNonRoot: true
      restartPolicy: Always
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "-1"
  name: ci-helper-app-secrets
  namespace: ci-helper-app
spec:
  dataFrom:
  - extract:
      key: staging/qe/ci-helper-app-secrets
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: appsre-stonesoup-vault
  target:
    creationPolicy: Owner
    deletionPolicy: Delete
    name: ci-helper-app-secrets
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: ci-helper-app
  namespace: ci-helper-app
spec:
  port:
    targetPort: 8080
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: ci-helper-app
