apiVersion: v1
kind: Namespace
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    operator.tekton.dev/prune.keep-since: "1440"
  name: rhtap-promotion-staging
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  name: appstudio-pipeline
  namespace: rhtap-promotion-staging
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  name: promotion-maintainers
  namespace: rhtap-promotion-staging
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: component-maintainer
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: prietyc123
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: sawood14012
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: rhopp
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: xinredhat
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  name: appstudio-pipelines-runner-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: appstudio-pipelines-runner
subjects:
- kind: ServiceAccount
  name: appstudio-pipeline
  namespace: rhtap-promotion-staging
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  name: appstudio-gitops-service-argocd-argocd-application-clusterrolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: appstudio-gitops-service-argocd-argocd-application-controller
subjects:
- kind: ServiceAccount
  name: appstudio-pipeline
  namespace: rhtap-promotion-staging
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "-1"
  name: infra-deployments-pr-creator
  namespace: rhtap-promotion-staging
spec:
  dataFrom:
  - extract:
      key: staging/build/tekton-ci/infra-deployments-pr-creator
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: appsre-stonesoup-vault
  target:
    creationPolicy: Owner
    deletionPolicy: Delete
    name: infra-deployments-pr-creator
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "-1"
  name: stage-test-e2e
  namespace: rhtap-promotion-staging
spec:
  dataFrom:
  - extract:
      key: staging/promotion/stage-test-e2e
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: appsre-stonesoup-vault
  target:
    creationPolicy: Owner
    deletionPolicy: Delete
    name: stage-test-e2e
---
apiVersion: pipelinesascode.tekton.dev/v1alpha1
kind: Repository
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  name: infra-deployments
  namespace: rhtap-promotion-staging
spec:
  concurrency_limit: 1
  url: https://github.com/redhat-appstudio/infra-deployments
