apiVersion: v1
kind: Namespace
metadata:
  labels:
    openshift.io/workload-monitoring: "true"
  name: o11y
spec: {}
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    openshift.io/prometheus-rule-evaluation-scope: leaf-prometheus
    openshift.io/workload-monitoring: "true"
  name: o11y-example-rule
  namespace: o11y
spec:
  groups:
  - name: example
    rules:
    - expr: sum by (code) (prometheus_http_requests_total)
      record: o11y_prometheus_http_requests_total
