apiVersion: v1
kind: ServiceAccount
metadata:
  name: perf-team-prometheus-reader-cluster-sa
  namespace: perf-team-prometheus-reader
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: perf-team-prometheus-reader-maintainers
  namespace: perf-team-prometheus-reader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: component-maintainer
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: konflux-performance
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sa-read-permissions-openshift-monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-monitoring-view
subjects:
- kind: ServiceAccount
  name: perf-team-prometheus-reader-cluster-sa
  namespace: perf-team-prometheus-reader
