apiVersion: v1
kind: Namespace
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    operator.tekton.dev/prune.keep-since: "1440"
  name: konflux-ci
---
apiVersion: v1
imagePullSecrets:
- name: quay-push-secret-konflux-ci
- name: registry-redhat-io-pull-secret
kind: ServiceAccount
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  name: appstudio-pipeline
secrets:
- name: quay-push-secret-konflux-ci
- name: registry-redhat-io-pull-secret
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  name: konflux-ci-maintainers
  namespace: konflux-ci
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: component-maintainer
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: konflux-build
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  name: appstudio-pipelines-runner-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: appstudio-pipelines-runner
subjects:
- kind: ServiceAccount
  name: appstudio-pipeline
  namespace: konflux-ci
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "-1"
  name: clair-in-ci-db-github-token
  namespace: konflux-ci
spec:
  dataFrom:
  - extract:
      key: production/integration-service/tekton-ci/clair-in-ci-db-github-token
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: appsre-stonesoup-vault
  target:
    creationPolicy: Owner
    deletionPolicy: Delete
    name: clair-in-ci-db-github-token
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "-1"
  name: github
  namespace: konflux-ci
spec:
  dataFrom:
  - extract:
      key: production/build/tekton-ci/github-read-only
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: appsre-stonesoup-vault
  target:
    creationPolicy: Owner
    deletionPolicy: Delete
    name: github
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "-1"
  name: infra-deployments-pr-creator
  namespace: konflux-ci
spec:
  dataFrom:
  - extract:
      key: staging/build/tekton-ci/infra-deployments-pr-creator
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: appsre-stonesoup-vault
  target:
    creationPolicy: Owner
    deletionPolicy: Delete
    name: infra-deployments-pr-creator
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "-1"
  name: quay-push-secret-konflux-ci
  namespace: konflux-ci
spec:
  dataFrom:
  - extract:
      key: staging/build/tekton-ci/quay-push-secret-konflux-ci
  refreshInterval: 15m
  secretStoreRef:
    kind: ClusterSecretStore
    name: appsre-stonesoup-vault
  target:
    creationPolicy: Owner
    deletionPolicy: Delete
    name: quay-push-secret-konflux-ci
    template:
      data:
        .dockerconfigjson: '{{ .config }}'
      engineVersion: v2
      type: kubernetes.io/dockerconfigjson
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "-1"
  name: registry-redhat-io-pull-secret
  namespace: konflux-ci
spec:
  dataFrom:
  - extract:
      key: production/build/tekton-ci/registry-redhat-io-pull-secret
  refreshInterval: 15m
  secretStoreRef:
    kind: ClusterSecretStore
    name: appsre-stonesoup-vault
  target:
    creationPolicy: Owner
    deletionPolicy: Delete
    name: registry-redhat-io-pull-secret
    template:
      data:
        .dockerconfigjson: '{{ .config }}'
      engineVersion: v2
      type: kubernetes.io/dockerconfigjson
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "-1"
  name: slack-webhook-notification-secret
  namespace: konflux-ci
spec:
  dataFrom:
  - extract:
      key: production/build/tekton-ci/slack-webhook-notification-secret
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: appsre-stonesoup-vault
  target:
    creationPolicy: Owner
    deletionPolicy: Delete
    name: slack-webhook-notification-secret
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "-1"
  name: snyk-shared-token
  namespace: konflux-ci
spec:
  dataFrom:
  - extract:
      key: staging/build/tekton-ci/snyk-shared-secret
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: appsre-stonesoup-vault
  target:
    creationPolicy: Owner
    deletionPolicy: Delete
    name: snyk-secret
---
apiVersion: pipelinesascode.tekton.dev/v1alpha1
kind: Repository
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  name: build-definitions
spec:
  url: https://github.com/konflux-ci/build-definitions
---
apiVersion: pipelinesascode.tekton.dev/v1alpha1
kind: Repository
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  name: ci-helper-app
spec:
  url: https://github.com/konflux-ci/ci-helper-app
---
apiVersion: pipelinesascode.tekton.dev/v1alpha1
kind: Repository
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  name: pipeline-service
spec:
  url: https://github.com/openshift-pipelines/pipeline-service
---
apiVersion: pipelinesascode.tekton.dev/v1alpha1
kind: Repository
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  name: pipeline-service-exporter
spec:
  url: https://github.com/openshift-pipelines/pipeline-service-exporter
---
apiVersion: pipelinesascode.tekton.dev/v1alpha1
kind: Repository
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  name: quality-dashboard
spec:
  url: https://github.com/konflux-ci/quality-dashboard
---
apiVersion: pipelinesascode.tekton.dev/v1alpha1
kind: Repository
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  name: sprayproxy
spec:
  url: https://github.com/konflux-ci/sprayproxy
---
apiVersion: pipelinesascode.tekton.dev/v1alpha1
kind: Repository
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  name: tekton-results
spec:
  url: https://github.com/openshift-pipelines/tektoncd-results
