apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  name: appsre-stonesoup-vault-rh-secret-store
spec:
  provider:
    vault:
      auth:
        appRole:
          path: approle
          roleId: d95dc71a-c0e7-158d-f4e5-75dd5c5c5557
          secretRef:
            key: secret-id
            name: cluster-secret-store-rh
            namespace: cluster-secret-store-rh
      path: stonesoup
      server: https://vault.ci.ext.devshift.net
      version: v2
---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  name: insights-appsre-vault
spec:
  conditions:
  - namespaces:
    - insights-management-tenant
  provider:
    vault:
      auth:
        appRole:
          path: approle
          roleId: dbbc1114-ba0e-38c4-fbf7-ce0cad753509
          secretRef:
            key: secret-id
            name: insights-appsre-vault
            namespace: appsre-vault
      path: insights
      server: https://vault.ci.ext.devshift.net
      version: v2
---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  name: rh-artifacts-bucket-writer-secret-store
spec:
  provider:
    vault:
      auth:
        appRole:
          path: approle
          roleId: d95dc71a-c0e7-158d-f4e5-75dd5c5c5557
          secretRef:
            key: secret-id
            name: cluster-secret-store-rh
            namespace: cluster-secret-store-rh
      path: app-sre/integrations-output/terraform-resources/appsrep09ue1/stonesoup-infra-production/rh-artifacts-bucket-writer
      server: https://vault.ci.ext.devshift.net
      version: v1
