apiVersion: v1
kind: Namespace
metadata:
  name: openshift-adp
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
  name: backup-s3-credentials
  namespace: openshift-adp
spec:
  dataFrom:
  - extract:
      conversionStrategy: Default
      decodingStrategy: None
      key: integrations-output/terraform-resources/appsres09ue1/stonesoup-infra-stage-backup/backup-stone-stg-host
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: appsre-vault
  target:
    creationPolicy: Owner
    deletionPolicy: Delete
    name: backup-s3-credentials
    template:
      data:
        cloud: |
          [default]
          aws_access_key_id={{ .aws_access_key_id }}
          aws_secret_access_key={{ .aws_secret_access_key }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: oadp-service-monitor
  name: oadp-service-monitor
  namespace: openshift-adp
spec:
  endpoints:
  - interval: 30s
    path: /metrics
    scheme: http
    targetPort: 8085
  selector:
    matchLabels:
      app.kubernetes.io/name: velero
---
apiVersion: oadp.openshift.io/v1alpha1
kind: DataProtectionApplication
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "-1"
  name: velero-aws
  namespace: openshift-adp
spec:
  backupLocations:
  - velero:
      config:
        kmsKeyId: 580d7f30-a37b-4708-a6e0-80f41ff8f190
        profile: default
        region: us-east-1
      credential:
        key: cloud
        name: backup-s3-credentials
      default: true
      objectStorage:
        bucket: backup-stone-stg-host
        prefix: velero
      provider: aws
  configuration:
    restic:
      enable: false
    velero:
      defaultPlugins:
      - openshift
      - aws
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
  name: openshift-adp
  namespace: openshift-adp
spec:
  targetNamespaces:
  - openshift-adp
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
  name: redhat-oadp-operator
  namespace: openshift-adp
spec:
  channel: stable-1.3
  installPlanApproval: Automatic
  name: redhat-oadp-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
---
apiVersion: velero.io/v1
kind: Schedule
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  name: backup-toolchain-host
  namespace: openshift-adp
spec:
  schedule: 30 1,13 * * *
  template:
    includedNamespaces:
    - toolchain-host-operator
    storageLocation: velero-aws-1
    ttl: 720h0m0s
  useOwnerReferencesInBackup: true
