apiVersion: v1
kind: Namespace
metadata:
  labels:
    app: multi-arch-controller
  name: multi-arch-controller
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: multi-arch-controller
  name: multi-arch-controller
  namespace: multi-arch-controller
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app: multi-arch-controller
  name: pipeline-anyuid-role
  namespace: multi-arch-controller
rules:
- apiGroups:
  - security.openshift.io
  resourceNames:
  - anyuid
  resources:
  - securitycontextconstraints
  verbs:
  - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: multi-arch-controller
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
  name: multi-arch-controller
rules:
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - get
- apiGroups:
  - ""
  - events.k8s.io
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - tekton.dev
  resources:
  - taskruns
  - taskruns/status
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: multi-arch-controller-maintainer
rules:
- apiGroups:
  - operators.coreos.com
  resources:
  - installplans
  verbs:
  - get
  - list
  - update
  - patch
- apiGroups:
  - ""
  resourceNames:
  - pipeline
  resources:
  - serviceaccounts
  verbs:
  - patch
  - get
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - get
  - list
  - watch
  - delete
- apiGroups:
  - tekton.dev
  resources:
  - pipelineruns
  verbs:
  - '*'
- apiGroups:
  - results.tekton.dev
  resources:
  - results
  - records
  verbs:
  - get
  - list
- apiGroups:
  - ""
  resources:
  - pods/portforward
  verbs:
  - create
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: grant-argocd
  namespace: multi-arch-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- kind: ServiceAccount
  name: openshift-gitops-argocd-application-controller
  namespace: openshift-gitops
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: multi-arch-controller-maintainers
  namespace: multi-arch-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: multi-arch-controller-maintainer
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: sbose78
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: stuartwdouglas
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app: multi-arch-controller
  name: pipeline-anyuid-rolebinding
  namespace: multi-arch-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pipeline-anyuid-role
subjects:
- kind: ServiceAccount
  name: pipeline
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: multi-arch-controller
  name: multi-arch-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: multi-arch-controller
subjects:
- kind: ServiceAccount
  name: multi-arch-controller
  namespace: multi-arch-controller
---
apiVersion: v1
data:
  host1.address: ec2-54-165-44-192.compute-1.amazonaws.com
  host1.arch: arm64
  host1.concurrency: "4"
  host1.secret: awskeys
  host1.user: ec2-user
  host2.address: ec2-34-227-115-211.compute-1.amazonaws.com
  host2.arch: arm64
  host2.concurrency: "4"
  host2.secret: awskeys
  host2.user: ec2-user
kind: ConfigMap
metadata:
  labels:
    build.appstudio.redhat.com/multi-arch-config: hosts
  name: host-config
  namespace: multi-arch-controller
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: multi-arch-controller
  name: multi-arch-controller
  namespace: multi-arch-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: multi-arch-controller
  template:
    metadata:
      labels:
        app: multi-arch-controller
    spec:
      containers:
      - args:
        - --v=4
        - --zap-log-level=4
        - --zap-devel=true
        - --zap-encoder=console
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: quay.io/redhat-user-workloads/rhtap-build-tenant/multi-arch-controller/multi-arch-controller:f7cbdb56f91a3240b3b1967b357931eaf39eec2d
        imagePullPolicy: Always
        name: multi-arch-controller
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 512Mi
      serviceAccountName: multi-arch-controller
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  labels:
    app: multi-arch-controller
  name: clean-shared-host
  namespace: multi-arch-controller
spec:
  description: This task will clean up after a build
  params:
  - name: SECRET_NAME
    type: string
  - name: TASKRUN_NAME
    type: string
  - name: NAMESPACE
    type: string
  - name: HOST
    type: string
  - name: USER
    type: string
  steps:
  - image: quay.io/sdouglas/registry:multiarch
    imagePullPolicy: Always
    name: provision
    script: |
      #!/bin/bash
      cd /tmp
      set -o verbose
      set -eu
      set -o pipefail
      cp $(workspaces.ssh.path)/id_rsa /tmp/master_key
      chmod 0400 /tmp/master_key
      export SSH_HOST=$(params.USER)@$(params.HOST)

      export USERNAME=$(echo $(params.TASKRUN_NAME)$(params.NAMESPACE) | md5sum | cut -d' ' -f1)

      ssh -i /tmp/master_key -o StrictHostKeyChecking=no $SSH_HOST sudo userdel -f -r -Z $USERNAME
  workspaces:
  - name: ssh
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  labels:
    app: multi-arch-controller
  name: provision-shared-host
  namespace: multi-arch-controller
spec:
  description: This task will create a new user on a host, setup ssh keys, and then
    create the relevant secret.
  params:
  - name: SECRET_NAME
    type: string
  - name: TASKRUN_NAME
    type: string
  - name: NAMESPACE
    type: string
  - name: HOST
    type: string
  - name: USER
    type: string
  steps:
  - image: quay.io/sdouglas/registry:multiarch
    imagePullPolicy: Always
    name: provision
    script: |
      #!/bin/bash
      cd /tmp
      set -o verbose
      set -eu
      set -o pipefail
      mkdir -p /root/.ssh
      cp $(workspaces.ssh.path)/id_rsa /tmp/master_key
      chmod 0400 /tmp/master_key
      export SSH_HOST=$(params.USER)@$(params.HOST)

      export USERNAME=$(echo $(params.TASKRUN_NAME)$(params.NAMESPACE) | md5sum | cut -d' ' -f1)

      cat >script.sh <<EOF
      rm -f $USERNAME $USERNAME.pub
      sudo adduser $USERNAME
      ssh-keygen -N '' -f $USERNAME
      sudo su $USERNAME -c 'mkdir /home/$USERNAME/.ssh'
      sudo su $USERNAME -c 'mkdir /home/$USERNAME/build'
      sudo cp $USERNAME.pub /home/$USERNAME/.ssh/authorized_keys
      sudo chown $USERNAME /home/$USERNAME/.ssh/authorized_keys
      EOF
      ssh -i /tmp/master_key -o StrictHostKeyChecking=no $SSH_HOST "bash -s" <script.sh
      ssh -i /tmp/master_key -o StrictHostKeyChecking=no $SSH_HOST cat $USERNAME  >id_rsa
      ssh -i /tmp/master_key -o StrictHostKeyChecking=no $SSH_HOST rm $USERNAME
      chmod 0400 id_rsa
      ssh -i id_rsa -o StrictHostKeyChecking=no $USERNAME@$(params.HOST) echo "test"
      KEY=$(cat id_rsa | base64 -w 0)
      HOST=$(echo $USERNAME@$(params.HOST) | base64 -w 0)
      DIR=$(echo /home/$USERNAME | base64 -w 0)

      cat >secret.yaml <<EOF
      apiVersion: v1
      data:
        id_rsa: "$KEY"
        host: "$HOST"
        build-dir: "$DIR"
      kind: Secret
      metadata:
        name: $(params.SECRET_NAME)
        namespace: $(params.NAMESPACE)
        labels:
          build.appstudio.redhat.com/multi-arch-required: "true"
      type: Opaque
      EOF
      kubectl create -f secret.yaml
  workspaces:
  - name: ssh
